sudo: required
services:
  - docker

before_install:
  - docker build -t silefort/react-test -f client/Dockerfile.dev ./client

script:
  - docker run -e CI=true silefort/react-test npm test

after_success:
  - docker build -t silefort/multi-client ./client
  - docker build -t silefort/multi-nginx ./nginx
  - docker build -t silefort/multi-server ./server
  - docker build -t silefort/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take these images and push them to docker hub
  - docker push silefort/multi-client
  - docker push silefort/multi-nginx
  - docker push silefort/multi-server
  - docker push silefort/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-098526689657"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

